name: JuggernautGame
author: A_Brave_Panda
version: 0.1
main: me.abravepanda.juggernaut.Main
commands:
    juggernaut:
        aliases: [jug]
        description: Juggernaut Command
        usage: 
          /<command>